
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.GroupLayout.Alignment;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

public class EnterAccount extends JDialog {
    private JPanel body;
    private JPanel bodyPanel;
    public JButton btnExit;
    public JButton btnLogin;
    private JPanel header;
    private JPanel inputsPanel;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JLabel lbAccountName;
    public JLabel lbE;
    private JLabel lbHaveAccount;
    public JLabel lbStartingMoney;
    private JLabel lbTitle;
    private JPanel mainPanel;
    private JPanel optionPanel;
    private ButtonGroup optionsGroup;
    public JRadioButton rbNo;
    public JRadioButton rbYes;
    public JTextField tfAccountName;
    public JTextField tfStartingMoney;

    public EnterAccount(Frame parent, boolean modal) {
        super(parent, modal);
        this.initComponents();
        this.optionsGroup.add(this.rbYes);
        this.optionsGroup.add(this.rbNo);
        UIManager.put("TitledBorder.border", new LineBorder(new Color(255, 255, 255), 1));
        this.setLocationRelativeTo((Component)null);
    }

    private void initComponents() {
        this.optionsGroup = new ButtonGroup();
        this.mainPanel = new JPanel();
        this.header = new JPanel();
        this.lbTitle = new JLabel();
        this.body = new JPanel();
        this.bodyPanel = new JPanel();
        this.optionPanel = new JPanel();
        this.lbHaveAccount = new JLabel();
        this.rbYes = new JRadioButton();
        this.rbNo = new JRadioButton();
        this.inputsPanel = new JPanel();
        this.jSeparator1 = new JSeparator();
        this.lbAccountName = new JLabel();
        this.tfAccountName = new JTextField();
        this.lbStartingMoney = new JLabel();
        this.lbE = new JLabel();
        this.tfStartingMoney = new JTextField();
        this.jSeparator2 = new JSeparator();
        this.btnLogin = new JButton();
        this.btnExit = new JButton();
        this.setDefaultCloseOperation(0);
        this.setMinimumSize(new Dimension(500, 370));
        this.setPreferredSize(new Dimension(500, 370));
        this.setResizable(false);
        this.mainPanel.setBackground(new Color(217, 219, 226));
        this.mainPanel.setLayout(new BorderLayout());
        this.header.setBackground(new Color(35, 44, 64));
        this.header.setPreferredSize(new Dimension(500, 50));
        this.header.setLayout(new FlowLayout(1, 5, 10));
        this.lbTitle.setFont(new Font("Roboto", 1, 24));
        this.lbTitle.setForeground(new Color(237, 246, 249));
        this.lbTitle.setText("Enter your account");
        this.header.add(this.lbTitle);
        this.mainPanel.add(this.header, "First");
        this.body.setOpaque(false);
        this.body.setLayout(new BoxLayout(this.body, 3));
        this.bodyPanel.setOpaque(false);
        this.bodyPanel.setLayout(new GridBagLayout());
        this.optionPanel.setBackground(new Color(255, 255, 255));
        this.optionPanel.setBorder(BorderFactory.createTitledBorder((Border)null, "Select an option", 2, 0, new Font("Roboto", 1, 14), new Color(67, 80, 100)));
        this.optionPanel.setOpaque(false);
        this.optionPanel.setPreferredSize(new Dimension(450, 100));
        this.optionPanel.setLayout(new FlowLayout(1, 30, 25));
        this.lbHaveAccount.setFont(new Font("Roboto", 0, 14));
        this.lbHaveAccount.setForeground(new Color(67, 80, 100));
        this.lbHaveAccount.setText("Do you have an account?");
        this.optionPanel.add(this.lbHaveAccount);
        this.rbYes.setBackground(new Color(217, 219, 226));
        this.rbYes.setFont(new Font("Roboto", 0, 14));
        this.rbYes.setForeground(new Color(67, 80, 100));
        this.rbYes.setSelected(true);
        this.rbYes.setText("Yes");
        this.optionPanel.add(this.rbYes);
        this.rbNo.setBackground(new Color(217, 219, 226));
        this.rbNo.setFont(new Font("Roboto", 0, 14));
        this.rbNo.setForeground(new Color(67, 80, 100));
        this.rbNo.setText("No");
        this.optionPanel.add(this.rbNo);
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = 1;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(10, 30, 10, 30);
        this.bodyPanel.add(this.optionPanel, gridBagConstraints);
        this.body.add(this.bodyPanel);
        this.inputsPanel.setOpaque(false);
        this.inputsPanel.setPreferredSize(new Dimension(500, 150));
        this.inputsPanel.setLayout(new GridBagLayout());
        this.jSeparator1.setBackground(new Color(35, 44, 64));
        this.jSeparator1.setForeground(new Color(35, 44, 64));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = 1;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(10, 30, 10, 30);
        this.inputsPanel.add(this.jSeparator1, gridBagConstraints);
        this.lbAccountName.setFont(new Font("Roboto", 0, 14));
        this.lbAccountName.setForeground(new Color(67, 80, 100));
        this.lbAccountName.setText("Enter your account name:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = 1;
        gridBagConstraints.anchor = 17;
        gridBagConstraints.insets = new Insets(0, 30, 0, 10);
        this.inputsPanel.add(this.lbAccountName, gridBagConstraints);
        this.tfAccountName.setPreferredSize(new Dimension(64, 30));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = 2;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(0, 30, 0, 10);
        this.inputsPanel.add(this.tfAccountName, gridBagConstraints);
        this.lbStartingMoney.setFont(new Font("Roboto", 0, 14));
        this.lbStartingMoney.setForeground(new Color(102, 102, 102));
        this.lbStartingMoney.setText("Enter starting money:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = 1;
        gridBagConstraints.anchor = 17;
        gridBagConstraints.insets = new Insets(0, 10, 0, 30);
        this.inputsPanel.add(this.lbStartingMoney, gridBagConstraints);
        this.lbE.setFont(new Font("Roboto", 1, 24));
        this.lbE.setForeground(new Color(102, 102, 102));
        this.lbE.setHorizontalAlignment(0);
        this.lbE.setText("£");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = 1;
        gridBagConstraints.insets = new Insets(0, 10, 0, 5);
        this.inputsPanel.add(this.lbE, gridBagConstraints);
        this.tfStartingMoney.setEnabled(false);
        this.tfStartingMoney.setPreferredSize(new Dimension(64, 30));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = 2;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(0, 0, 0, 30);
        this.inputsPanel.add(this.tfStartingMoney, gridBagConstraints);
        this.jSeparator2.setBackground(new Color(35, 44, 64));
        this.jSeparator2.setForeground(new Color(35, 44, 64));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = 1;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(0, 30, 5, 30);
        this.inputsPanel.add(this.jSeparator2, gridBagConstraints);
        this.btnLogin.setBackground(new Color(35, 44, 64));
        this.btnLogin.setFont(new Font("Roboto", 0, 14));
        this.btnLogin.setForeground(new Color(255, 255, 255));
        this.btnLogin.setText("Login to the system");
        this.btnLogin.setBorderPainted(false);
        this.btnLogin.setPreferredSize(new Dimension(75, 15));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = 1;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(0, 30, 10, 10);
        this.inputsPanel.add(this.btnLogin, gridBagConstraints);
        this.btnExit.setBackground(new Color(35, 44, 64));
        this.btnExit.setFont(new Font("Roboto", 0, 14));
        this.btnExit.setForeground(new Color(255, 255, 255));
        this.btnExit.setText("Get out of the system");
        this.btnExit.setBorderPainted(false);
        this.btnExit.setPreferredSize(new Dimension(75, 15));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = 1;
        gridBagConstraints.weightx = 0.5D;
        gridBagConstraints.weighty = 0.5D;
        gridBagConstraints.insets = new Insets(0, 10, 10, 30);
        this.inputsPanel.add(this.btnExit, gridBagConstraints);
        this.body.add(this.inputsPanel);
        this.mainPanel.add(this.body, "Center");
        GroupLayout layout = new GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(this.mainPanel, -1, -1, 32767));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(this.mainPanel, -1, -1, 32767));
        this.pack();
    }
}
