
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.border.LineBorder;

public class Principal extends JFrame {
    public JButton btnExit;
    public JButton btnPortfolio;
    public JButton btnSearchStock;
    public JButton btnTradeStock;
    private JPanel decorative1;
    private JPanel decorative2;
    private JPanel mainPanel;
    private JPanel panel;

    public Principal() {
        this.initComponents();
        this.setLocationRelativeTo((Component)null);
        this.setExtendedState(6);
    }

    private void initComponents() {
        this.mainPanel = new JPanel();
        this.decorative1 = new JPanel();
        this.panel = new JPanel();
        this.btnPortfolio = new JButton();
        this.btnSearchStock = new JButton();
        this.btnTradeStock = new JButton();
        this.btnExit = new JButton();
        this.decorative2 = new JPanel();
        this.setDefaultCloseOperation(3);
        this.setTitle("Stock Simulator");
        this.setMinimumSize(new Dimension(800, 600));
        this.mainPanel.setBackground(new Color(217, 219, 225));
        this.mainPanel.setLayout(new BorderLayout());
        this.decorative1.setBackground(new Color(35, 45, 63));
        this.decorative1.setPreferredSize(new Dimension(700, 50));
        GroupLayout decorative1Layout = new GroupLayout(this.decorative1);
        this.decorative1.setLayout(decorative1Layout);
        decorative1Layout.setHorizontalGroup(decorative1Layout.createParallelGroup(Alignment.LEADING).addGap(0, 800, 32767));
        decorative1Layout.setVerticalGroup(decorative1Layout.createParallelGroup(Alignment.LEADING).addGap(0, 50, 32767));
        this.mainPanel.add(this.decorative1, "First");
        this.panel.setOpaque(false);
        this.panel.setLayout(new GridBagLayout());
        this.btnPortfolio.setBackground(new Color(66, 78, 100));
        this.btnPortfolio.setFont(new Font("Roboto", 1, 18));
        this.btnPortfolio.setForeground(new Color(255, 255, 255));
        this.btnPortfolio.setText("Portfolio");
        this.btnPortfolio.setBorder(new LineBorder(new Color(67, 79, 100), 1, true));
        this.btnPortfolio.setCursor(new Cursor(12));
        this.btnPortfolio.setHorizontalTextPosition(0);
        this.btnPortfolio.setMargin(new Insets(0, 0, 0, 0));
        this.btnPortfolio.setOpaque(true);
        this.btnPortfolio.setPreferredSize(new Dimension(150, 150));
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        this.panel.add(this.btnPortfolio, gridBagConstraints);
        this.btnSearchStock.setBackground(new Color(66, 78, 100));
        this.btnSearchStock.setFont(new Font("Roboto", 1, 18));
        this.btnSearchStock.setForeground(new Color(255, 255, 255));
        this.btnSearchStock.setText("Search stock");
        this.btnSearchStock.setBorder(new LineBorder(new Color(67, 79, 100), 1, true));
        this.btnSearchStock.setCursor(new Cursor(12));
        this.btnSearchStock.setMargin(new Insets(0, 0, 0, 0));
        this.btnSearchStock.setOpaque(true);
        this.btnSearchStock.setPreferredSize(new Dimension(150, 150));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        this.panel.add(this.btnSearchStock, gridBagConstraints);
        this.btnTradeStock.setBackground(new Color(66, 78, 100));
        this.btnTradeStock.setFont(new Font("Roboto", 1, 18));
        this.btnTradeStock.setForeground(new Color(255, 255, 255));
        this.btnTradeStock.setText("Trade stock");
        this.btnTradeStock.setBorder(new LineBorder(new Color(67, 79, 100), 1, true));
        this.btnTradeStock.setCursor(new Cursor(12));
        this.btnTradeStock.setMargin(new Insets(0, 0, 0, 0));
        this.btnTradeStock.setOpaque(true);
        this.btnTradeStock.setPreferredSize(new Dimension(150, 150));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        this.panel.add(this.btnTradeStock, gridBagConstraints);
        this.btnExit.setBackground(new Color(66, 78, 100));
        this.btnExit.setFont(new Font("Roboto", 1, 18));
        this.btnExit.setForeground(new Color(255, 255, 255));
        this.btnExit.setText("Sign out");
        this.btnExit.setBorder(new LineBorder(new Color(67, 79, 100), 1, true));
        this.btnExit.setCursor(new Cursor(12));
        this.btnExit.setMargin(new Insets(0, 0, 0, 0));
        this.btnExit.setOpaque(true);
        this.btnExit.setPreferredSize(new Dimension(150, 150));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        this.panel.add(this.btnExit, gridBagConstraints);
        this.mainPanel.add(this.panel, "Center");
        this.decorative2.setBackground(new Color(35, 45, 63));
        this.decorative2.setPreferredSize(new Dimension(700, 50));
        GroupLayout decorative2Layout = new GroupLayout(this.decorative2);
        this.decorative2.setLayout(decorative2Layout);
        decorative2Layout.setHorizontalGroup(decorative2Layout.createParallelGroup(Alignment.LEADING).addGap(0, 800, 32767));
        decorative2Layout.setVerticalGroup(decorative2Layout.createParallelGroup(Alignment.LEADING).addGap(0, 50, 32767));
        this.mainPanel.add(this.decorative2, "Last");
        GroupLayout layout = new GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(this.mainPanel, -1, -1, 32767));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(this.mainPanel, -1, -1, 32767));
        this.pack();
    }
}
